config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails.application.routes.draw do

  use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/user/:id/verify", to: 'users#verify', as: 'user_verify'
  post "/user/:id/verify", to: 'users#verify', as: 'user_verify_code'
  post "/user/:id/resend", to: 'users#resend', as: 'user_resend'
  get "/user/:id/send_code", to: 'users#send_code', as: 'user_send_code'
  constraints(AuthConstraint.new) do
    resources :blogs
    root 'blogs#index', via: :get
    match "/blog/:id/verify_post", to: 'blogs#verify_post', as: 'blog_verify', via: [:get, :post]
    match "/blog/:id/verify_code", to: 'blogs#verify_code', as: 'blog_verify_code', via: [:get, :post]
    match "/blog/:id/send_code", to: 'blogs#send_code', as: 'blog_send_code', via: [:get, :post]
    post "/blog/:id/resend", to: 'blogs#resend', as: 'blog_resend'
    match "/my_blog_list", to: 'blogs#my_blog_list', as: 'my_blog_list', via: [:get]
  end

  resources :users, only: [:new, :create, :index, :show]
  root 'blogs#index', via: :get
  match "/sessions/new", to: 'sessions#new',as: "/login_user", via: [:get,:post]


    match 'auth/:provider/callback', to: 'sessions#create', via: [:get,:post]
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:new,:create,:index, :destroy]
 
end

app/models/blog.rb
class Blog < ApplicationRecord
	scope :published, -> { where('article_status = ?', "Published") }
	scope :drafts, -> { where('article_status = ?', "Drafts") }
  validates :title, presence: true
  validates :description, presence: true
  validates :content, presence: true


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :send_code, :verify_code, :resend]
  before_action :doorkeeper_authorize!, except: [:index, :show]

  def index
    # List only published Blogs
    @blogs = Blog.published

  end

  def my_blog_list
    # List only the current users blogs
    @blogs = Blog.where(user_id: current_user)

  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @user = current_user
    # Use service class to generate Authy code and send it via app or sms
    send_token = TwilioAuthy.new(@user).send_code_authy(@user.authy_id)
    respond_to do |format|
      if @blog.save
        flash[:notice] = 'Blog has been saved as Drafts'
        format.js  { render :send_code, locals: {blog_id: @blog.id} }
      else
        format.js { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

# Method to send Authy code after editing blog
  def send_code
    @user = current_user
    # Use service class to generate Authy code and send it via app or sms
    send_token = TwilioAuthy.new(@user).send_code_authy(@user.authy_id)
    respond_to do |format|
      format.js  { render :send_code, locals: {blog_id: @blog.id} }
    end
  end

# Method to verify code after adding/editing blog
  def verify_code
    @user = current_user
     # Use service class to verify Authy code
    @authy_signup = TwilioAuthy.new(@user).verify_code_authy(@user.authy_id, params[:token] )
    if @authy_signup
      @blog.update(verify: true)
      # Publish the blog when after 2FA
      @blog.update(article_status: "Published")
      flash[:notice] = 'Article has been published'
    else
      flash.now[:danger] = "Incorrect code, please try again"
      render :send_code, locals: {blog_id: @blog.id}
    end
  end

# Method to resend verification code after adding/editing blog
  def resend
    @user = current_user
      # Use service class to resend Authy code
    TwilioAuthy.new(@user).send_code_authy(@user.authy_id)
    flash[:notice] = 'Verification code re-sent'
    render :send_code, locals: {blog_id: @blog.id}
  end  

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.js { render :show, locals: {blog_id: @blog.id, access_token: session[:access_token]} , notice: 'Blog was successfully updated.' }
        flash[:notice] = 'Article has been updated'
      else
        flash[:notice] = 'Article has not been updated'
        format.js { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url(access_token: session[:access_token]), notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:user_id, :title, :description, :content, :article_status, :verify)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_index.html.erb
<div id="blog">
  <div class = "box blog"> 
    <div class="row">
      <div class = "col-5">

        <%if flash[:notice]%>
          <p class = "alert alert-success alert-dark alert-dismissible fade show" id="notice"><%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
          </button></p>
          <%else%>
          <p></p>
        <%end%>  
      </div>
    </div>  
    <%@user = current_user%>
      <br>
    <%if @user && @user.provider%>  
      <div class="row">
        <div class = "col-5">
         <strong>Want to start blogging! Register as a NewBlog User</strong>
        </div>
      </div> 
    <%end%>  
    <hr>
    <div class="row">

      <div class = "col-3">
        <h3>
          <strong>
            Blogs
          </strong>
        </h3>
      </div>
      <%if @user%>
        <div class = "col-4">
          <h3>
            <%= link_to "View my Blogs", my_blog_list_path(access_token: session[:access_token]),remote: true, class: "btn btn-primary" %>
          </h3>
        </div>
        <div class = "col-5"> 
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign me out!", signout_path, class: "btn btn-warning" %>
        </div>
      <%else%>
        <div class = "col-5"> 
          <%= link_to "Sign me in", new_session_path, class: "btn btn-primary" %> <strong> as New Blog user to start Blogging</strong>
        </div>        
      <%end%>


    </div>
    <hr>  
    <% @blogs.each do |blog| %>

      <div class="row">
        <div class = "col-5">
          <h4><strong><%= blog.title%></strong> by <i><%= User.find_by(id: blog.user_id).name%></i></h4>
        </div>
      </div>
      <div class="row"> 
        <div class = "col-5">
        <h6><strong>Title:</strong>
          <%= blog.title %></h6>
        </div>  
      </div> 
      <div class="row">
        <div class = "col-5">
           <i><strong>Description:</strong></i>
            <i><%= blog.description %></i>
        </div>
      </div>
      <div class="row">
        <div class = "col-5">
        <%if current_user%>
          <strong><%=link_to 'Read More', blog_path(id: blog.id, access_token: session[:access_token]), remote: true, class: "btn-sm btn-primary"%></strong>
        <%else%>     
          <strong><%=link_to 'Sign me in', new_session_path, class: "btn-sm btn-primary"%></strong> to read more!
        <%end%>

        </div>
      </div>
      <hr>
    <% end %>
    <p>
      <%if @user && @user.provider == "NewBlog"%>
        <div class="row">
          <div class = "col-5">
            <%= link_to 'New Blog',new_blog_path(access_token: session[:access_token]), remote: true, class: "btn btn-success"%>
          </div>
        </div>
      <%else%>  
      <%end%>   
    </p>   
  </div>
</div>

app/views/blogs/_my_blog_list.html.erb
<div id="blog">  
  <table class = "box table table-condensed "> 
  <div class="row">
    <div class = "col-5">
      <%if notice%>
        <p class = "alert alert-success alert-dark alert-dismissible" id="notice"><%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
        </button></p>
        <%else%>
        <p></p>
      <%end%>  
    </div>
  </div>   
  <%if @blogs.blank?%>
   <h4><strong>You havent saved any blogs</strong>
  <%end%> 
  <% @blogs.each do |blog| %> 
    <div class="row">
      <div class = "col-5">
        <h4><strong><%= blog.title%></strong> by <i><%= User.find_by(id: blog.user_id).name%></i></h4>
      </div>
    </div>
    <div class="row"> 
      <div class = "col-5">
      <h6><strong>Title:</strong>
        <%= blog.title %></h6>
      </div>  
    </div> 
    <div class="row">
      <div class = "col-5">
         <i><strong>Description:</strong></i>
          <i><%= blog.description %></i>
      </div>
    </div>
    <div class="row">  
      <div class = "col-5">
      <i><strong>Article status:</strong></i>
        <%= blog.article_status %>
      </div>  
    </div> 


    <%if blog.user_id == current_user.id %>
      <div class="row"> 
        <div class = "col-5">
          <%if blog.article_status == "Drafts"%>
            <%= link_to 'Publish Article', blog_send_code_path(id: blog.id, access_token: session[:access_token]), remote: true, class: "btn btn-success"%>
          <%end%>
        </div>

        <div class = "col-5">
          <%= link_to 'Edit', edit_blog_path(blog, access_token: session[:access_token]), remote: true, class: "btn btn-primary" %> 
        </div>    
       </div>
      <%end%> 
   <hr>
  <%end%>  
    <hr>
 
    <hr>
    <div class="row">
      <div class = "col-5"></td>
        <div class = "col-5">
          <%= link_to 'Back', blogs_path(access_token: session[:access_token]), class: "btn btn-info" %>
        </div>
      </div>    
  </table> 
</div>

app/views/blogs/_send_code.html.erb
<div id="blog">
	<div class="row">
    <div class = "col-5">

      <%if flash[:notice]%>
        <p class = "alert alert-info alert-dark alert-dismissible fade show" id="notice"><%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
        </button></p>
        <%else%>
        <p></p>
      <%end%>  
    </div>
  </div> 
  <br>
  <h3>Just To Be Safe...</h1>
	<p>
    Your account has been created, but we need to make sure you're a human
    in control of the phone number you gave us. Can you please enter the 
    verification code we just sent to your Twilio Authy app or mobile?
	</p>
	<%= form_tag blog_verify_code_path(id: @blog.id,access_token: session[:access_token]),:remote=> 'true' do %>
	  <div class="form-group">
	    <strong><%= label_tag :code, "Verification Code:" %></strong>
	    <%= text_field_tag :token, '', class: "form-control" %>
	  </div>
	  <button type="submit" class="btn btn-primary">Verify Code</button>
	<% end -%>
	<hr>
	<%= form_tag blog_resend_path(id: @blog.id,access_token: session[:access_token]),:remote=> 'true' do %>
		<div>
			<button type="submit" class="btn btn-primary">Resend Code</button>
	  </div>
	<hr>	
	<% end -%>
	<%=link_to 'Back', blogs_path(access_token: session[:access_token]), class: "btn btn-info"%>
	<br>
</div>

app/views/blogs/create.js.erb
$('#blog').html("<%= j(render 'send_code.html.erb') %>")`

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/edit.js.erb
$("#blog").html("<%= escape_javascript(render(:partial => "form")) %>");

app/views/blogs/index.html.erb
<div id="blog">
  <div class = "box blog"> 
    <div class="row">
      <div class = "col-5">

        <%if flash[:notice]%>
          <p class = "alert alert-success alert-dark alert-dismissible fade show" id="notice"><%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
          </button></p>
          <%else%>
          <p></p>
        <%end%>  
      </div>
    </div>  
    <%@user = current_user%>
    <hr> 
 
    <hr>
    <div class="row">
      <div class = "col-3">
        <h3>
          <strong>
            Blogs
          </strong>
        </h3>
      </div>
      <%if @user%>
        <div class = "col-4">
          <%if @user.provider == "NewBlog"%>  
            <h3>
              <%= link_to "View my Blogs", my_blog_list_path(access_token: session[:access_token]),remote: true, class: "btn btn-primary" %>
            </h3> 
          <%else%>  
            <strong>Want to start blogging! Register as a Blog User</strong>
          <%end%>       
        </div>
        <div class = "col-5"> 
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign me out!", signout_path, class: "btn btn-warning" %>
        </div>
      <%else%>
        <div class = "col-5"> 
          <%= link_to "Sign me in", new_session_path, class: "btn btn-primary" %> <strong> as New Blog user to start Blogging</strong>
        </div>        
      <%end%>


    </div>
    <hr>  
    <% @blogs.each do |blog| %>

      <div class="row">
        <div class = "col-5">
          <h4><strong><%= blog.title%></strong> by <i><%= User.find_by(id: blog.user_id).name%></i></h4>
        </div>
      </div>
      <div class="row"> 
        <div class = "col-5">
        <h6><strong>Title:</strong>
          <%= blog.title %></h6>
        </div>  
      </div> 
      <div class="row">
        <div class = "col-5">
           <i><strong>Description:</strong></i>
            <i><%= blog.description %></i>
        </div>
      </div>
      <div class="row">
        <div class = "col-5">
        <%if current_user%>
          <strong><%=link_to 'Read More', blog_path(id: blog.id, access_token: session[:access_token]), remote: true, class: "btn-sm btn-primary"%></strong>
        <%else%>     
          <strong><%=link_to 'Sign me in', new_session_path, class: "btn-sm btn-primary"%></strong> to read more!
        <%end%>

        </div>
      </div>
      <hr>
    <% end %>
    <p>
      <%if @user && @user.provider == "NewBlog"%>
        <div class="row">
          <div class = "col-5">
            <%= link_to 'New Blog',new_blog_path(access_token: session[:access_token]), remote: true, class: "btn btn-success"%>
          </div>
        </div>
      <%else%>  
      <%end%>   
    </p>   
  </div>
</div>

app/views/blogs/index.js.erb
$("#blog").html("<%= escape_javascript(render(:partial => "index")) %>");

app/views/blogs/my_blog_list.js.erb
$("#blog").html("<%= escape_javascript(render(:partial => "my_blog_list")) %>");

app/views/blogs/new.html.erb
<%= render 'form', blog: @blog, params: {access_token: session[:access_token]} %>

app/views/blogs/resend.js.erb
$("#blog").html("<%= escape_javascript(render(:partial => "show")) %>");

app/views/blogs/send_code.js.erb
$("#blog").html("<%= escape_javascript(render(:partial => "send_code")) %>");

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blog.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>Article status:</strong>
  <%= @blog.article_status %>
</p>

<p>
  <strong>Verify:</strong>
  <%= @blog.verify %>
</p>

<p>
  <strong>Users:</strong>
  <%= @blog.users %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/verify_code.js.erb
$("#blog").html("<%= escape_javascript(render(:partial => "show")) %>");