config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails.application.routes.draw do

  use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/user/:id/verify", to: 'users#verify', as: 'user_verify'
  post "/user/:id/verify", to: 'users#verify', as: 'user_verify_code'
  post "/user/:id/resend", to: 'users#resend', as: 'user_resend'
  get "/user/:id/send_code", to: 'users#send_code', as: 'user_send_code'
  constraints(AuthConstraint.new) do
    resources :blogs
    root 'blogs#index', via: :get
    match "/blog/:id/verify_post", to: 'blogs#verify_post', as: 'blog_verify', via: [:get, :post]
    match "/blog/:id/verify_code", to: 'blogs#verify_code', as: 'blog_verify_code', via: [:get, :post]
    match "/blog/:id/send_code", to: 'blogs#send_code', as: 'blog_send_code', via: [:get, :post]
    post "/blog/:id/resend", to: 'blogs#resend', as: 'blog_resend'
    match "/my_blog_list", to: 'blogs#my_blog_list', as: 'my_blog_list', via: [:get]
  end

  resources :users, only: [:new, :create, :index, :show]
  root 'blogs#index', via: :get
  match "/sessions/new", to: 'sessions#new',as: "/login_user", via: [:get,:post]


    match 'auth/:provider/callback', to: 'sessions#create', via: [:get,:post]
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:new,:create,:index, :destroy]
 
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  # Bcrypt encryption for password
  has_secure_password
  has_many :blogs

  # Associated Doorkeeper models to generate UID, Access Token 
  has_many :access_grants, class_name: "Doorkeeper::AccessGrant",
                           foreign_key: :resource_owner_id,
                           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens, class_name: "Doorkeeper::AccessToken",
                           foreign_key: :resource_owner_id,
                           dependent: :delete_all
  has_one :application, class_name: "Doorkeeper::Application",
                           foreign_key: :uid
                    
  validates :email,  presence: true, format: { with: /\A.+@.+$\Z/ }
  validates :password_digest, presence: true
  validates :name, presence: true

 # Method to login external Oauth Providers
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password_digest = BCrypt::Password.create(auth.uid)
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # # GET /users/1
  # # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
        
    if @user.save
      # Use service class to generate Authy code and send it via app or sms
      @authy_signup = TwilioAuthy.new(@user).sign_up_authy
      if @authy_signup
        session[:pre_auth_user_id] = @user.id
        redirect_to user_send_code_path(id: session[:pre_auth_user_id], access_token: session[:access_token])
      else
        flash[:notice] = "Authy Registration Failed. Please try again"
        redirect_to new_user_path
      end
    else
      flash[:notice] = "Incorrect User Credentials"
      render :new
    end

  end

  def send_code
    @user = User.find_by(id: session[:pre_auth_user_id]) 
  end  

  def verify
    @user = User.find_by(id: session[:pre_auth_user_id])
    
    @authy_signup = TwilioAuthy.new(@user).verify_code_authy(@user.authy_id, params[:token] )
    if @authy_signup
      # Mark the user as verified for get /user/:id
      @user.update(verified: true)
      oauth_token = OauthToken.new(@user).check_token      
      if oauth_token
        session[:user_id] = @user.id
        session[:access_token] = @user.oauth_token  
        redirect_to root_path(access_token: session[:access_token]) 
      else
        redirect_to new_user_path
      end  
    else
      flash.now[:danger] = "Incorrect code, please try again"
      redirect_to user_send_code_path(id: session[:pre_auth_user_id], access_token: session[:access_token])
    end
  end

  def resend
    @user = User.find_by(id: session[:pre_auth_user_id])
    # Authy::API.request_sms(id: @user.authy_id)
    TwilioAuthy.new(@user).send_code_authy(@user.authy_id)
    flash[:notice] = 'Verification code re-sent'
    redirect_to user_verify_path(id: @user.id)
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:email, :country_code, :phone, :password, :password_confirmation, :provider )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, validate: true) do |form| %>
  <div class="row">
    <div class = "col-5">

      <%if flash[:notice]%>
        <p class = "alert alert-info alert-dark alert-dismissible fade show" id="notice"><%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
        </button></p>
        <%else%>
        <p></p>
      <%end%>  
    </div>
  </div>  
  <p></p>
  <table class = "table table-condensed box-form">  
  <thead>
  <tr class="row">
    <td class = "col-5">
      <h3><strong>New User</strong></h3>  
    </td>
  </tr>  
  <tr class="row">
    <td class = "col-5">
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </td>
  </tr>
  </thead>
  <tbody>
  <tr class="row">
    <td class = "col-5">
      <%= form.label :name %>
    </td>  
    <td class = "col-5">
      <%= form.text_field :name, id: :user_name %>
    </td>
  </tr>  

  <tr class="row">
    <td class = "col-5">
      <%= form.label :email %>
    </td>  
    <td class = "col-5">
      <%= form.text_field :email, id: :user_email %>
    </td>
  </tr>

    <tr class="row">
      <td class = "col-5">
        <%= form.label :password %>
      </td>  
      <td class = "col-5">
        <%= form.password_field :password, id: :user_password %>
      </td>
    </tr>

    <tr class="row">
      <td class = "col-5">
        <%= form.label :password_confirmation %>
      </td>  
      <td class = "col-5">
        <%= form.password_field :password_confirmation, id: :user_password %>
      </td>
    </tr>

    <tr class="row">
      <td class = "col-5">
        <%= form.label :country_code %>
      </td>  
      <td class = "col-5">
        <%= form.text_field :country_code, id: :user_country_code, required: true %>
      </td>
    </tr>

    <tr class="row">
      <td class = "col-5">
        <%= form.label :phone %>
      </td> 
      <td class = "col-5"> 
        <%= form.text_field :phone, id: :user_phone, required: true  %>
      </td>
    </tr>
    <div class="field">
      <%= form.hidden_field :provider, :value => "NewBlog" %>
    </div>

    <div>
      <tr class="row">
        <td class = "col-5">
          <%= form.submit 'Sign up', class: "btn btn-success" %>
        </td>
        <td class = "col-5">
          <%= link_to 'Back', new_session_path, class: "btn btn-info" %>
        </td>
      </tr>
    </div>
  <% end %>
  </tbody>
</table> 

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<hr>
<div>Try Signing up Again</div><hr><div><%=link_to 'Register Me', new_user_path, class: "btn btn-primary"%></div><hr>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/send_code.html.erb
<div class="row">
  <div class = "col-5">

    <%if flash[:notice]%>
      <p class = "alert alert-success alert-dark alert-dismissible fade show" id="notice"><%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
      </button></p>
      <%else%>
      <p></p>
    <%end%>  
  </div>
</div>  
<hr> 
<h3>Just To Be Safe...</h1>
	<p>
	    Your account has been created, but we need to make sure you're a human
	    in control of the phone number you gave us. Can you please enter the 
	    verification code we just sent to your Twilio Authy app or mobile?
	</p>
	<%= form_tag user_verify_code_path(@user.id) do %>
	  <div class="form-group">
	    <strong><%= label_tag :code, "Verification Code:" %></strong>
	    <%= text_field_tag :token, '', class: "form-control" %>
	  </div>
	  <button type="submit" class="btn btn-primary">Verify Token</button>
	<% end -%>
	<hr>
	<%= form_tag user_resend_path(@user.id) do %>
		<div>
	  	<button type="submit" class="btn btn-primary">Resend Token</button>
	  </div>
	<hr>
	<br>	
		<%=link_to 'Back', root_path%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
  <div class = "col-5">

    <%if flash[:notice]%>
      <p class = "alert alert-success alert-dark alert-dismissible fade show" id="notice"><%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
      </button></p>
      <%else%>
      <p></p>
    <%end%>  
  </div>
</div>  
<hr> 
<h1><%= @user.name %></h1>
<p>Account Status: <% if @user.verified? %>Verified<% else -%>Not Verified<% end -%>
<% if !@user.verified? %>
<p>
  <%=link_to "Verify your account now", user_verify_path(id: @user.id)%>

</p>
<% end -%>